CREATE TABLE IF NOT EXISTS merchant_quotation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    quotation_no VARCHAR(64) NOT NULL COMMENT '报价单号',
    merchant_id BIGINT NOT NULL COMMENT '商户租户ID',
    merchantName VARCHAR(128) NOT NULL COMMENT '商户名称',
    target_app_id BIGINT DEFAULT NULL COMMENT '目标应用ID',
    target_app_code VARCHAR(32) NOT NULL DEFAULT 'NEXIS' COMMENT '目标应用编码',
    target_tenant_id BIGINT DEFAULT NULL COMMENT '目标租户ID',
    target_project_name VARCHAR(128) DEFAULT NULL COMMENT '目标项目名称',
    target_site_name VARCHAR(128) DEFAULT NULL COMMENT '目标工地名称',
    target_user_name VARCHAR(64) DEFAULT NULL COMMENT '目标联系人',
    target_user_phone VARCHAR(32) DEFAULT NULL COMMENT '目标联系电话',
    customer_name VARCHAR(64) NOT NULL COMMENT '客户姓名',
    customer_phone VARCHAR(32) DEFAULT NULL COMMENT '客户电话',
    warehouse_id BIGINT DEFAULT NULL COMMENT '计划发货仓库ID',
    warehouse_name VARCHAR(128) DEFAULT NULL COMMENT '计划发货仓库名称',
    logistics_company VARCHAR(128) DEFAULT NULL COMMENT '计划物流公司',
    quotation_status VARCHAR(32) NOT NULL COMMENT '报价状态',
    valid_until DATETIME DEFAULT NULL COMMENT '有效期截止时间',
    item_count INT NOT NULL DEFAULT 0 COMMENT '商品总件数',
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '报价总金额',
    remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_merchant_quotation_tenant_no (tenant_id, quotation_no)
) COMMENT='商户报价单主表';

CREATE TABLE IF NOT EXISTS merchant_quotation_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    quotation_id BIGINT NOT NULL COMMENT '报价单ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    product_name VARCHAR(128) NOT NULL COMMENT '商品名称',
    sku_code VARCHAR(64) DEFAULT NULL COMMENT '商品SKU',
    unit VARCHAR(32) DEFAULT NULL COMMENT '单位',
    quantity INT NOT NULL COMMENT '数量',
    quotation_price DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '报价单价',
    line_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '行金额',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_merchant_quotation_item_quotation_id (quotation_id)
) COMMENT='商户报价单明细表';
