CREATE TABLE IF NOT EXISTS merchant_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    order_no VARCHAR(64) NOT NULL COMMENT '订单号',
    merchant_id BIGINT NOT NULL COMMENT '商户租户ID',
    merchant_name VARCHAR(128) NOT NULL COMMENT '商户名称',
    target_app_id BIGINT DEFAULT NULL COMMENT '目标应用ID',
    target_app_code VARCHAR(32) NOT NULL DEFAULT 'NEXIS' COMMENT '目标应用编码',
    target_tenant_id BIGINT DEFAULT NULL COMMENT '目标租户ID',
    target_project_name VARCHAR(128) DEFAULT NULL COMMENT '目标项目名称',
    target_site_name VARCHAR(128) DEFAULT NULL COMMENT '目标工地名称',
    target_user_name VARCHAR(64) DEFAULT NULL COMMENT '目标联系人',
    target_user_phone VARCHAR(32) DEFAULT NULL COMMENT '目标联系电话',
    customer_name VARCHAR(64) NOT NULL COMMENT '客户姓名',
    customer_phone VARCHAR(32) DEFAULT NULL COMMENT '客户电话',
    delivery_address VARCHAR(255) DEFAULT NULL COMMENT '收货地址',
    warehouse_id BIGINT DEFAULT NULL COMMENT '发货仓库ID',
    warehouse_name VARCHAR(128) DEFAULT NULL COMMENT '发货仓库名称',
    logistics_company VARCHAR(128) DEFAULT NULL COMMENT '物流公司',
    tracking_no VARCHAR(128) DEFAULT NULL COMMENT '运单号',
    shipped_at DATETIME DEFAULT NULL COMMENT '发货时间',
    shipping_remark VARCHAR(255) DEFAULT NULL COMMENT '发货备注',
    order_status VARCHAR(32) NOT NULL COMMENT '订单状态',
    item_count INT NOT NULL DEFAULT 0 COMMENT '商品总件数',
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '订单总金额',
    remark VARCHAR(255) DEFAULT NULL COMMENT '订单备注',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_merchant_order_tenant_order_no (tenant_id, order_no)
) COMMENT='商户订单主表';

CREATE TABLE IF NOT EXISTS merchant_order_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    product_name VARCHAR(128) NOT NULL COMMENT '商品名称',
    sku_code VARCHAR(64) DEFAULT NULL COMMENT '商品SKU',
    unit VARCHAR(32) DEFAULT NULL COMMENT '单位',
    quantity INT NOT NULL COMMENT '购买数量',
    sale_price DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '成交单价',
    line_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '行金额',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_merchant_order_item_order_id (order_id)
) COMMENT='商户订单明细表';
