CREATE TABLE IF NOT EXISTS merchant_product (
    id BIGINT PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    product_name VARCHAR(128) NOT NULL COMMENT '商品名称',
    category_code VARCHAR(64) NOT NULL COMMENT '品类编码',
    sku_code VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    main_image_url VARCHAR(512) DEFAULT NULL COMMENT '商品主图URL',
    brand_name VARCHAR(128) DEFAULT NULL COMMENT '品牌名称',
    spec_model VARCHAR(128) DEFAULT NULL COMMENT '规格型号',
    material VARCHAR(128) DEFAULT NULL COMMENT '材质',
    product_description VARCHAR(1000) DEFAULT NULL COMMENT '商品描述',
    unit VARCHAR(32) DEFAULT NULL COMMENT '单位',
    sale_price DECIMAL(18,2) DEFAULT NULL COMMENT '销售价',
    stock_quantity INT DEFAULT NULL COMMENT '库存数量',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_merchant_product_tenant_name (tenant_id, product_name)
) COMMENT='商户商品表';

CREATE TABLE IF NOT EXISTS merchant_product_region_price (
    id BIGINT PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '商户租户ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    region_level TINYINT NOT NULL COMMENT '区域级别 1省 2市 3区县',
    region_code VARCHAR(32) NOT NULL COMMENT '生效行政区编码',
    region_name VARCHAR(64) NOT NULL COMMENT '生效行政区名称',
    province_code VARCHAR(32) DEFAULT NULL COMMENT '省级行政区编码',
    province_name VARCHAR(64) DEFAULT NULL COMMENT '省级行政区名称',
    city_code VARCHAR(32) DEFAULT NULL COMMENT '市级行政区编码',
    city_name VARCHAR(64) DEFAULT NULL COMMENT '市级行政区名称',
    district_code VARCHAR(32) DEFAULT NULL COMMENT '区县行政区编码',
    district_name VARCHAR(64) DEFAULT NULL COMMENT '区县行政区名称',
    sale_price DECIMAL(18,2) NOT NULL COMMENT '区域销售价',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_merchant_product_region_price_scope (tenant_id, product_id, region_level, region_code),
    KEY idx_merchant_product_region_price_product (product_id),
    KEY idx_merchant_product_region_price_region (region_level, region_code)
) COMMENT='商户商品区域价表';
