CREATE TABLE IF NOT EXISTS warehouse_registry (
    id BIGINT PRIMARY KEY COMMENT '主键',
    app_code VARCHAR(32) NOT NULL COMMENT '应用编码 NEXIS/WSGM/PRIMELOAD-MARKETPLACE/PRIMELOAD-CLOUD-WAREHOUSE',
    tenant_id BIGINT NOT NULL COMMENT '当前租户ID',
    warehouse_code VARCHAR(64) NOT NULL COMMENT '仓库编码',
    warehouse_name VARCHAR(128) NOT NULL COMMENT '仓库名称',
    warehouse_type VARCHAR(32) NOT NULL COMMENT '仓库类型 PROJECT_WAREHOUSE/MERCHANT_WAREHOUSE/CLOUD_WAREHOUSE/COMPREHENSIVE_WAREHOUSE/TENANT_WAREHOUSE',
    default_flag TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认仓 1是 0否',
    owner_type VARCHAR(32) NOT NULL COMMENT '业务方类型 PROJECT/MERCHANT/CLOUD_WAREHOUSE/COMPREHENSIVE_WAREHOUSE/TENANT',
    owner_app_code VARCHAR(32) NOT NULL COMMENT '业务方所属应用编码',
    owner_tenant_id BIGINT NOT NULL COMMENT '业务方租户ID',
    contact_name VARCHAR(64) DEFAULT NULL COMMENT '联系人',
    contact_phone VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
    warehouse_address VARCHAR(255) DEFAULT NULL COMMENT '仓库地址',
    province_code VARCHAR(32) DEFAULT NULL COMMENT '省级行政区编码',
    province_name VARCHAR(64) DEFAULT NULL COMMENT '省级行政区名称',
    city_code VARCHAR(32) DEFAULT NULL COMMENT '市级行政区编码',
    city_name VARCHAR(64) DEFAULT NULL COMMENT '市级行政区名称',
    district_code VARCHAR(32) DEFAULT NULL COMMENT '区县行政区编码',
    district_name VARCHAR(64) DEFAULT NULL COMMENT '区县行政区名称',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_warehouse_registry_tenant_code (app_code, tenant_id, warehouse_code),
    KEY idx_warehouse_registry_owner (owner_app_code, owner_tenant_id),
    KEY idx_warehouse_registry_tenant_default (app_code, tenant_id, default_flag)
) COMMENT='数字仓库注册表';
