CREATE TABLE IF NOT EXISTS warehouse_inventory_record (
    id BIGINT PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    warehouse_id BIGINT DEFAULT NULL COMMENT '仓库ID',
    warehouse_name VARCHAR(128) DEFAULT NULL COMMENT '仓库名称',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    product_name VARCHAR(128) NOT NULL COMMENT '商品名称',
    sku_code VARCHAR(64) DEFAULT NULL COMMENT '商品SKU',
    change_type VARCHAR(32) NOT NULL COMMENT '变更类型 INITIAL_IN/MANUAL_IN/MANUAL_OUT/ORDER_OUT/ORDER_CANCEL_IN',
    change_quantity INT NOT NULL COMMENT '变更数量',
    before_quantity INT NOT NULL COMMENT '变更前库存',
    after_quantity INT NOT NULL COMMENT '变更后库存',
    source_type VARCHAR(64) DEFAULT NULL COMMENT '来源类型',
    source_id BIGINT DEFAULT NULL COMMENT '来源ID',
    source_no VARCHAR(64) DEFAULT NULL COMMENT '来源单号',
    remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_warehouse_inventory_record_product (tenant_id, product_id, created_at),
    KEY idx_warehouse_inventory_record_warehouse (tenant_id, warehouse_id, created_at),
    KEY idx_warehouse_inventory_record_source (tenant_id, source_type, source_id)
) COMMENT='仓储库存流水表';
