CREATE TABLE IF NOT EXISTS tenant_registry (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    app_id BIGINT NOT NULL DEFAULT 0 COMMENT '应用ID',
    app_code VARCHAR(32) NOT NULL DEFAULT 'WSGM' COMMENT '应用编码',
    parent_tenant_id BIGINT DEFAULT NULL COMMENT '父级租户ID。PMHUB 中项目可挂到公司或集团租户下',
    tenant_code VARCHAR(64) NOT NULL COMMENT '租户编码',
    tenant_name VARCHAR(128) NOT NULL COMMENT '租户名称',
    tenant_type VARCHAR(32) NOT NULL COMMENT '租户类型',
    tenant_source VARCHAR(32) DEFAULT NULL COMMENT '租户来源，例如 PRIMELOAD_SELF_OPERATED',
    project_address VARCHAR(255) DEFAULT NULL COMMENT '项目地址',
    province_code VARCHAR(32) DEFAULT NULL COMMENT '省级行政区编码',
    province_name VARCHAR(64) DEFAULT NULL COMMENT '省级行政区名称',
    city_code VARCHAR(32) DEFAULT NULL COMMENT '市级行政区编码',
    city_name VARCHAR(64) DEFAULT NULL COMMENT '市级行政区名称',
    district_code VARCHAR(32) DEFAULT NULL COMMENT '区县行政区编码',
    district_name VARCHAR(64) DEFAULT NULL COMMENT '区县行政区名称',
    manager_name VARCHAR(64) DEFAULT NULL COMMENT '项目负责人',
    manager_phone VARCHAR(32) DEFAULT NULL COMMENT '项目负责人电话',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0禁用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    self_operated_unique_key BIGINT GENERATED ALWAYS AS (CASE WHEN tenant_source = 'PRIMELOAD_SELF_OPERATED' AND deleted = 0 THEN app_id ELSE NULL END) STORED COMMENT '好料自营唯一约束键',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_tenant_registry_app_code (app_id, tenant_code),
    KEY idx_tenant_registry_parent (parent_tenant_id),
    UNIQUE KEY uk_tenant_registry_self_operated (self_operated_unique_key)
) COMMENT='租户注册表';
