CREATE TABLE IF NOT EXISTS nexis_site_work_scope (
    id BIGINT PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '所属租户ID',
    project_id BIGINT NOT NULL COMMENT '项目ID',
    site_id BIGINT NOT NULL COMMENT '标段/工地ID',
    participant_company_id BIGINT NOT NULL COMMENT '参建单位ID',
    scope_type VARCHAR(32) NOT NULL COMMENT '范围类型 CODE_RANGE/MILESTONE_RANGE/AREA_RANGE/PIPE_SEGMENT/BUILDING_FLOOR_RANGE',
    scope_name VARCHAR(128) DEFAULT NULL COMMENT '范围名称',
    scope_start_code VARCHAR(64) DEFAULT NULL COMMENT '范围起点编码',
    scope_end_code VARCHAR(64) DEFAULT NULL COMMENT '范围终点编码',
    scope_remark VARCHAR(255) DEFAULT NULL COMMENT '范围说明',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_nexis_site_work_scope_tenant_site (tenant_id, site_id, status),
    KEY idx_nexis_site_work_scope_company (participant_company_id),
    KEY idx_nexis_site_work_scope_project (project_id)
) COMMENT='Nexis标段施工范围表';
