CREATE TABLE IF NOT EXISTS nexis_worker (
    id BIGINT PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '所属租户ID',
    project_id BIGINT NOT NULL COMMENT '项目ID',
    site_id BIGINT NOT NULL COMMENT '标段/工地ID',
    participant_company_id BIGINT NOT NULL COMMENT '参建单位ID',
    work_scope_id BIGINT DEFAULT NULL COMMENT '施工范围ID',
    team_id BIGINT DEFAULT NULL COMMENT '班组ID',
    worker_name VARCHAR(64) NOT NULL COMMENT '工人姓名',
    worker_phone VARCHAR(32) DEFAULT NULL COMMENT '工人手机号',
    id_card_no VARCHAR(32) DEFAULT NULL COMMENT '身份证号',
    job_type VARCHAR(32) DEFAULT NULL COMMENT '工种编码',
    job_name VARCHAR(64) DEFAULT NULL COMMENT '工种名称',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_nexis_worker_tenant_site (tenant_id, site_id, status),
    KEY idx_nexis_worker_project (project_id),
    KEY idx_nexis_worker_company (participant_company_id),
    KEY idx_nexis_worker_scope (work_scope_id),
    KEY idx_nexis_worker_team (team_id),
    KEY idx_nexis_worker_name_phone (tenant_id, worker_name, worker_phone)
) COMMENT='Nexis工人表';
