CREATE TABLE IF NOT EXISTS project_external_link (
    id BIGINT PRIMARY KEY COMMENT '主键',
    source_project_tenant_id BIGINT NOT NULL COMMENT '承包方本地项目租户ID',
    source_organization_tenant_id BIGINT DEFAULT NULL COMMENT '承包方公司租户ID',
    external_participant_company_id BIGINT DEFAULT NULL COMMENT '本地项目中代表外部上级单位的参建单位ID',
    target_organization_tenant_id BIGINT NOT NULL COMMENT '待认领或已认领的正式上级公司租户ID',
    target_project_tenant_id BIGINT DEFAULT NULL COMMENT '审核时选定的正式上级项目租户ID',
    external_owner_name_snapshot VARCHAR(128) DEFAULT NULL COMMENT '申请时的外部上级单位名称快照',
    external_project_name_snapshot VARCHAR(128) DEFAULT NULL COMMENT '申请时的外部项目名称快照',
    contract_scope_name_snapshot VARCHAR(128) DEFAULT NULL COMMENT '申请时的承包范围名称快照',
    link_status VARCHAR(24) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING LINKED REJECTED CANCELLED UNLINKED',
    share_scope VARCHAR(24) NOT NULL DEFAULT 'SUMMARY' COMMENT '数据共享范围，默认SUMMARY',
    requested_by BIGINT NOT NULL COMMENT '申请人用户ID',
    reviewed_by BIGINT DEFAULT NULL COMMENT '审核人用户ID',
    reviewed_at DATETIME DEFAULT NULL COMMENT '审核时间',
    review_remark VARCHAR(255) DEFAULT NULL COMMENT '审核备注',
    unlinked_by BIGINT DEFAULT NULL COMMENT '解除关联用户ID',
    unlinked_at DATETIME DEFAULT NULL COMMENT '解除关联时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_project_external_link_source (source_project_tenant_id, link_status, deleted),
    KEY idx_project_external_link_target_org (target_organization_tenant_id, link_status, deleted),
    KEY idx_project_external_link_target_project (target_project_tenant_id, link_status, deleted)
) COMMENT='外部上级项目认领与承包段关联';
