CREATE TABLE IF NOT EXISTS project_team (
    id BIGINT PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '所属租户ID',
    project_id BIGINT NOT NULL COMMENT '项目ID',
    site_id BIGINT NOT NULL COMMENT '标段/工地ID',
    participant_company_id BIGINT NOT NULL COMMENT '参建单位ID',
    work_scope_id BIGINT DEFAULT NULL COMMENT '施工范围ID',
    team_name VARCHAR(128) NOT NULL COMMENT '班组名称',
    team_code VARCHAR(64) DEFAULT NULL COMMENT '班组编码',
    leader_name VARCHAR(64) DEFAULT NULL COMMENT '班组长姓名',
    leader_phone VARCHAR(32) DEFAULT NULL COMMENT '班组长手机号',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_project_team_site_name (site_id, team_name),
    KEY idx_project_team_tenant_site (tenant_id, site_id, status),
    KEY idx_project_team_project (project_id),
    KEY idx_project_team_company (participant_company_id),
    KEY idx_project_team_scope (work_scope_id)
) COMMENT='施工总管班组表';
