CREATE TABLE IF NOT EXISTS project_worker_entry (
    id BIGINT PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '所属租户ID',
    entry_no VARCHAR(64) NOT NULL COMMENT '实名进场单号',
    project_id BIGINT NOT NULL COMMENT '项目ID',
    site_id BIGINT DEFAULT NULL COMMENT '标段/工地ID，可为空',
    participant_company_id BIGINT NOT NULL COMMENT '参建单位ID',
    work_scope_id BIGINT DEFAULT NULL COMMENT '施工范围ID',
    team_id BIGINT DEFAULT NULL COMMENT '班组ID',
    worker_id BIGINT NOT NULL COMMENT '工人ID',
    real_name_status VARCHAR(32) NOT NULL COMMENT '实名状态',
    entry_status VARCHAR(32) NOT NULL COMMENT '进场状态',
    entered_at DATETIME DEFAULT NULL COMMENT '实际进场时间',
    exited_at DATETIME DEFAULT NULL COMMENT '实际退场时间',
    remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_project_worker_entry_no (entry_no),
    KEY idx_project_worker_entry_tenant_site (tenant_id, site_id, status),
    KEY idx_project_worker_entry_project (project_id),
    KEY idx_project_worker_entry_company (participant_company_id),
    KEY idx_project_worker_entry_scope (work_scope_id),
    KEY idx_project_worker_entry_team (team_id),
    KEY idx_project_worker_entry_worker (worker_id),
    KEY idx_project_worker_entry_status (tenant_id, entry_status, real_name_status)
) COMMENT='Nexis工人实名进场表';
