CREATE TABLE IF NOT EXISTS project_worker_attendance (
    id BIGINT PRIMARY KEY COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '所属租户ID',
    attendance_no VARCHAR(64) NOT NULL COMMENT '考勤单号',
    attendance_date DATE NOT NULL COMMENT '考勤日期',
    project_id BIGINT NOT NULL COMMENT '项目ID',
    site_id BIGINT NOT NULL COMMENT '标段/工地ID',
    participant_company_id BIGINT NOT NULL COMMENT '参建单位ID',
    work_scope_id BIGINT DEFAULT NULL COMMENT '施工范围ID',
    team_id BIGINT DEFAULT NULL COMMENT '班组ID',
    worker_id BIGINT NOT NULL COMMENT '工人ID',
    entry_id BIGINT NOT NULL COMMENT '实名进场记录ID',
    attendance_status VARCHAR(32) NOT NULL COMMENT '考勤状态',
    check_in_at DATETIME NOT NULL COMMENT '签到时间',
    check_out_at DATETIME DEFAULT NULL COMMENT '签退时间',
    remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_project_worker_attendance_no (attendance_no),
    UNIQUE KEY uk_project_worker_attendance_worker_day (tenant_id, worker_id, attendance_date),
    KEY idx_project_worker_attendance_site_day (tenant_id, site_id, attendance_date),
    KEY idx_project_worker_attendance_team_day (tenant_id, team_id, attendance_date),
    KEY idx_project_worker_attendance_entry (entry_id),
    KEY idx_project_worker_attendance_status (tenant_id, attendance_status)
) COMMENT='施工总管工人考勤表';
