CREATE TABLE IF NOT EXISTS workflow_task (
    id BIGINT PRIMARY KEY COMMENT '主键',
    app_id BIGINT NOT NULL COMMENT '应用ID',
    app_code VARCHAR(32) NOT NULL COMMENT '应用编码',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    workflow_type VARCHAR(64) NOT NULL COMMENT '流程类型',
    task_title VARCHAR(128) NOT NULL COMMENT '任务标题',
    task_content VARCHAR(1000) DEFAULT NULL COMMENT '任务内容',
    source_type VARCHAR(64) DEFAULT NULL COMMENT '来源业务类型',
    source_id BIGINT DEFAULT NULL COMMENT '来源业务ID',
    applicant_user_id BIGINT NOT NULL COMMENT '申请人ID',
    assignee_user_id BIGINT NOT NULL COMMENT '审批人ID',
    task_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态 PENDING/APPROVED/REJECTED',
    reviewed_by BIGINT DEFAULT NULL COMMENT '审批人ID',
    reviewed_at DATETIME DEFAULT NULL COMMENT '审批时间',
    review_remark VARCHAR(255) DEFAULT NULL COMMENT '审批备注',
    action_url VARCHAR(255) DEFAULT NULL COMMENT '处理地址',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记 0未删 1已删',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_workflow_task_assignee (app_id, tenant_id, assignee_user_id, task_status, id),
    KEY idx_workflow_task_applicant (app_id, tenant_id, applicant_user_id, id),
    KEY idx_workflow_task_source (app_id, tenant_id, source_type, source_id)
) COMMENT='工作流任务表';
